/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Seringue (1).glb");
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={392.832}
        near={303.32}
        fov={39.598}
        position={[-0.247, 0.21, 0.19]}
        rotation={[-0.688, -0.788, -0.528]}
        scale={0.001}
      />
      <group scale={0.001}>
        <group position={[9.344, 67.789, 0]}>
          <group position={[-9.344, -47.323, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Corps_Graduation_1STEP_1.geometry}
              material={materials["Clear Rough Plastic White #1"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Corps_Graduation_1STEP_2.geometry}
              material={materials["Clear Rough Plastic White #1"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joint_10301100_1STEP_1.geometry}
            material={materials["Hard Rough Plastic Black #1"]}
            position={[-9.344, 20.414, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Couleur_10301100STEP_1.geometry}
            material={materials["Hard Rough Plastic Red #1"]}
            position={[-9.344, -67.789, 0]}
            rotation={[0, 0.47, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Seringue (1).glb");
